schema=1
version=1.2.6
publishedAt=2026-08-20T11:05:45Z
notesUrl=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/tag/v1.2.6
asset.android.file=SyncDroid-Mesh-1.2.6-Android.apk
asset.android.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.6/SyncDroid-Mesh-1.2.6-Android.apk
asset.android.sha256=c43f0a6ca46854ab7d5b8b4c0404d152c1337e3963b2e215247acdf909d5d1da
asset.android.size=55877710
asset.macos-arm64.file=SyncTosh-1.2.6-macOS-arm64.dmg
asset.macos-arm64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.6/SyncTosh-1.2.6-macOS-arm64.dmg
asset.macos-arm64.sha256=3f06bea3f96cc7c2b32b7cee495e99dbcfcce6eece112c6cb52f6f879868f5f4
asset.macos-arm64.size=140037584
asset.windows-x64.file=SyncDows-1.2.6-Windows-x64.exe
asset.windows-x64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.6/SyncDows-1.2.6-Windows-x64.exe
asset.windows-x64.sha256=b64fd343dd6d51ef66a212e5b3a13e66fddec67047f68894a9d16269a5a3fde5
asset.windows-x64.size=129112338
