schema=1
version=1.2.7
publishedAt=2026-08-22T00:58:29Z
notesUrl=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/tag/v1.2.7
asset.android.file=SyncDroid-Mesh-1.2.7-Android.apk
asset.android.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.7/SyncDroid-Mesh-1.2.7-Android.apk
asset.android.sha256=6c3c9414c327a3c4e834f37c090274ba78ee3557b749d24d63e6e0353e9eec3e
asset.android.size=55877710
asset.macos-arm64.file=SyncTosh-1.2.7-macOS-arm64.dmg
asset.macos-arm64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.7/SyncTosh-1.2.7-macOS-arm64.dmg
asset.macos-arm64.sha256=dd117be2e9965ca29adc7722d290d7fc33ecf6b2cad237e6a54aed2f8c9894a4
asset.macos-arm64.size=140027066
asset.windows-x64.file=SyncDows-1.2.7-Windows-x64.exe
asset.windows-x64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.7/SyncDows-1.2.7-Windows-x64.exe
asset.windows-x64.sha256=aafd772aa10c7828aeddbdcfb79f8696ceba1fc60e62eb898c6c6cff5c5cf684
asset.windows-x64.size=129140448
